HTML/CSS & JavaScript capstone project
jossi30/Module1-Capstone pull request #1
Opened 2023-01-11 18:57 UTC by jossi30

A seminar page built using HTML/CSS and Javascript, to fit different screen sizes.

2023-01-11 22:46 UTC, franclobo requested changes
Hi @jossi30, 

# ♻️ REQUIRED CHANGES ♻️ 

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/211932392-0b16fa91-47ed-4f60-acf8-959a4a16cc2d.gif)

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 
- Professional README file ✔️ 

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-01-11 22:46 UTC, franclobo commented on style1.css
> +    justify-content: center;
- [ ] To be similar to the original design please correct the alignment of the elements in the footer (logo aligned to the left and text aligned to the right) 👇🏽 

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/211928717-82d4c01d-0503-4f0b-870b-ee1ad7be3a55.png) | ![image](https://user-images.githubusercontent.com/58642949/211928522-fa96d378-be6d-421b-965f-dcd512086256.png) |

2023-01-11 22:46 UTC, franclobo commented on index.html
> +    </footer>
- [ ] The home page in the mobile version finishes with the Feature Speakers, kindly remove the others sections in the mobile version 👇🏽 

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/211929614-b36e3edc-065b-46dd-a3c3-73046a69ca23.png) | ![image](https://user-images.githubusercontent.com/58642949/211929732-fe55930a-b88e-44d0-8427-ca00c36984e6.png) |

2023-01-11 22:46 UTC, franclobo commented on index.html
> +    </section>
- [ ] The main program section in the desktop version finishes with the SEE THE WHOLE PROGRAM link while the mobile version finishes with JOIN CC GLOBAL SUMMIT 2015 button, please 🙏🏽 fix it to be similar to the original design 👇🏽 
- [ ] Kindly correct the dimension and the background to be similar to the original design.
- [ ] When the user hovers over the items a withe border appears, please add this effect to your design and correct the design of the items for a better user interface.

| Original design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/211930544-e2b141d6-0386-41dc-a92e-e7dbf17d1eb3.png)  ![image](https://user-images.githubusercontent.com/58642949/211930762-1f7af288-0223-4f4c-9de3-1fea4ba51ebd.png) | ![image](https://user-images.githubusercontent.com/58642949/211930644-a00bdd6e-c0e6-4117-894c-02c1d1af2f97.png) ![image](https://user-images.githubusercontent.com/58642949/211930874-7f87ee17-9aaf-4a4b-a0d3-fb0f15e0333c.png) |

2023-01-11 22:46 UTC, franclobo commented on about.html
> +        <div><img src="img/menu-svgrepo-com.svg" class="openbtn" onclick="openNav()" alt=""></div>
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

2023-01-11 22:46 UTC, franclobo commented on about.html
> +         <img src="img/pngwing.com.png" alt="">
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

2023-01-11 22:46 UTC, franclobo commented on about.html
> +        <img class="partners-img" src="img/nba (2).png" alt="">
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

2023-01-11 22:46 UTC, franclobo commented on index.html
> +        <div><img src="img/menu-svgrepo-com.svg" class="openbtn" onclick="openNav()" alt=""></div>
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

2023-01-11 22:46 UTC, franclobo commented on index.html
> +          <img src="img/lecture-conference-svgrepo-com.svg" />
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

2023-01-11 22:46 UTC, franclobo commented on index.html
> +          <img src="img/conference-hall-svgrepo-com.svg" />
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

2023-01-11 22:46 UTC, franclobo commented on index.html
> +          <img src="img/forum.svg" />
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

2023-01-11 22:46 UTC, franclobo commented on index.html
> +          <img src="img/business-suitcase-svgrepo-com.svg" />
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

2023-01-11 22:46 UTC, franclobo commented on index.html
> +          <img src="img/network-group-svgrepo-com.svg" />
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

2023-01-11 22:46 UTC, franclobo commented on index.html
> +          <img class="partners-img" src="img/dallas-cowboys.png" alt="">
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

2023-01-11 22:46 UTC, franclobo commented on index.html
> +      <img src="img/pngwing.com.png" />
- [ ] All the `img` tag should have the `alt` attribute that describes the content of the image for the best practices of HTML and CSS.

2023-01-12 16:19 UTC, danmainah approved these changes
Hi @jossi30 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 16:19 UTC, danmainah commented on about.html
> +         </div>
- [ ] [optional][ It would have been nice if you ensured matched with the design given , this ensure adhering to the project requirement
![image](https://user-images.githubusercontent.com/61408860/212121274-ce58a138-9425-4207-a982-09cca4622dc5.png)
 below is a comparison between your design and the design given


Behance Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/212121609-de6adf5b-2c63-484f-939d-904f8833cf03.png) | ![image](https://user-images.githubusercontent.com/61408860/212121694-4597bbcf-ccd6-48ad-9154-cf4f958f6819.png)

2023-01-12 16:21 UTC, merged